load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "client",
    srcs = [
        "doc.go",
        "sidecar_client.go",
    ],
    importpath = "github.com/byte4ever/rules_gitops/testing/it_sidecar/client",
    visibility = ["//visibility:public"],
)
