#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o xtrace

bindir=$(cd "$(dirname "$0")" && pwd)
cd "${bindir}"

# Verify interactive workflow.
MYNAMESPACE="${USER}"

kubectl create namespace "${MYNAMESPACE}" || true
kubectl create namespace hwteam || true

bazel run //helloworld:mynamespace.apply
kubectl -n "${MYNAMESPACE}" wait --timeout=60s \
  --for=condition=Available deployment/helloworld

bazel run //helloworld:mynamespace.delete

rm -rf cloud

bazel run //helloworld:canary.gitops
bazel run //helloworld:release.gitops

# Apply everything generated by gitops.
kubectl apply -f cloud -R

# Wait for readiness.
kubectl -n hwteam wait --timeout=60s \
  --for=condition=Available \
  deployment/helloworld \
  deployment/helloworld-canary
